### ISSUE TITLE
Automate update of gh-pages

### ISSUE THREAD

**Issue by zuphilip** [aurimasv/z2csl#10]
Should we automate the update of the `gh-pages` fork whenever the `master` fork is updated? My plan would be to automate the following steps
1. Trigger when a new commit is pushed or merged into the `master` branch
2. Copy the files `typeMap.xml`, `typeMap.xsl`, `typeMap.css` from the `master` branch into the `gh-pages` branch
3. Commit the differences (if any) in the `gh-pages` with some meaningful commit message.

I guess that with some webhook and shell scripting this could be done, but I don't know exactly... Any reactions about the plan are also welcome. (Maybe there are other mechanisms to synchronize some files between different git branches.)

**Comment by zuphilip** [comment]
We should consider to change publishing GitHub pages as it is possible now: https://github.com/blog/2228-simpler-github-pages-publishing. One can change from `gh-pages` to `master` or also just the `docs` folder from `master`:

![](https://cloud.githubusercontent.com/assets/849592/17724056/d516076e-640c-11e6-8086-ce1d246a87d2.png)

However, this change can only been done from @aurimasv...

**Comment by gracile-fr** [comment]
That would be great ! http://aurimasv.github.io/z2csl/typeMap.xml is out of date. Any news from @aurimasv ?

**Comment by zuphilip** [comment]
What exactly is outdated? There were some recent commits (to update to 4.0.29.10.SOURCE) but it might be that #12 would be important as well... (sorry I forgot the details)

**Comment by gracile-fr** [comment]
Not a big issue at the moment, but the page shows "Generated with Zotero 4.0.21.SOURCE ", it would be better to retrieve the mapping from the latest release (even if there's no change) to avoid ambiguities.
#12 is a manual update ; #13 would provide automatic updates…

**Comment by zuphilip** [comment]
@gracile-fr I updated the website now and finished the work on the update script.

However, it seems that nowadays the `gh-pages` fork is unnecessary and give us just more work. Thus, I will leave this open, because my comment https://github.com/aurimasv/z2csl/issues/10#issuecomment-240563710 . It would be great if @aurimasv can spent some minutes here and switch the website creation to the `master` branch.

**Comment by aurimasv** [comment]
Sorry for the delay. I changed to publish from master branch and changed the theme to Minimal. I could not select docs/ folder, since the content is being published to <username>.github.io domain. (I think you have to publish on a different domain to use docs/)

BTW, I'm ok transferring ownership of this project to someone else, if anyone wants to take it over. (Maybe to the Zotero project if Zotero is ok with that)

**Comment by zuphilip** [comment]
Okay, thank you! Then we have now also a website from the README file: https://aurimasv.github.io/z2csl/ (or was this there also before?). I cannot say anything about transfering ownership, but maybe this should also be discussed somewhere else (zotero-dev mailing list?).

**Comment by gracile-fr** [comment]
(poke @zotero @dstillman )

**Comment by gracile-fr** [comment]
> BTW, I'm ok transferring ownership of this project to someone else, if anyone wants to take it over. (Maybe to the Zotero project if Zotero is ok with that)

poke @zotero @dstillman
