### ISSUE TITLE
Erroneous field?

### ISSUE THREAD

**Issue by mvolz** [aurimasv/z2csl#4]
The live version of this says that ISBN is a valid field for videoRecording... but not film. Seems a bit weird.  Thoughts? :)

**Comment by aurimasv** [comment]
That would be quite odd, but I haven't tested this in some time and related code was altered in Zotero proper recently, so I wouldn't say it's impossible. I won't be able to take a look at this in the near future.

**Comment by mvolz** [comment]
Looking at this source code: https://github.com/zotero/zotero/blob/4.0/chrome/content/zotero/xpcom/connector/typeSchemaData.js

I confirmed that ISBN is valid for videoRecording but not film. But that file hasn't changed in 4 years. Is the schema defined somewhere else then? (This probably isn't the right place for this ticket...)

**Comment by zuphilip** [comment]
The database schema is defined here https://github.com/zotero/zotero/blob/4.0/resource/schema/system.sql . AFAIK new fields and changes to the database schema will be possible again after Zotero 5.0 is released. There are some issues for what to do then collected at https://github.com/avram/zotero-bits/issues .
